In [58]:
from sklearn.linear_model import LogisticRegression as lreg, LinearRegression as linreg
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle

In [59]:
path = r'C:\Users\Subhajit Paul\Downloads\archive\heart.csv'
path2 = r'C:\Users\Subhajit Paul\Downloads\archive\o2Saturation.csv'
heart = pd.read_csv(path)
o2 = pd.read_csv(path2)
heart = heart.join(o2['O2'])


age : age of the person  
sex : gender of the person  
cp : Chest Pain type  
    Value 1: typical angina  
    Value 2: atypical angina  
    Value 3: non-anginal pain  
    Value 4: asymptomatic  
trtbps : resting blood pressure (in mm Hg)  
chol : cholestoral in mg/dl fetched via BMI sensor  
fbs : (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)  
restecg : resting electrocardiographic results  
    Value 0: normal  
    Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)  
    Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria  
thalachh : maximum heart rate achieved  
exng : exercise induced angina (1 = yes; 0 = no)  
oldpeak : Previous peak  
O2 : Level of oxygen  


In [60]:
Y = heart[['cp']].values / np.max(Y)

In [61]:
X = heart.drop(['cp', 'output', 'caa', 'slp', 'thall', 'target'], axis = 1).values

In [63]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.15, random_state=0)
y_test = Y_test.reshape((Y_test.shape[0]))
y_train = Y_train.reshape((Y_train.shape[0])) 
X_train, X_test = X_train.astype(np.float16), X_test.astype(np.float16)

In [64]:
for i in range(10):
    X_train[:,i] = X_train[:,i] / np.max(X_train[:,i])
    X_test[:,i] = X_test[:,i] / np.max(X_test[:,i])

In [66]:
model_lin = linreg()

In [68]:
model_lin.fit(X_train, y_train)

LinearRegression()

In [72]:
model_lin.score(X_train, y_train)

0.23730297085886798

In [53]:
model = lreg(max_iter=20000, verbose=2).

In [54]:
model.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(max_iter=20000, verbose=2)

In [13]:
predictions = model.predict(X_test)

In [55]:
model.score(X_test, y_test)

0.8478260869565217

In [52]:
model.predict_proba([X_test[3]])

array([[0.95710252, 0.04289748]])

In [18]:
with open('HA_Model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [17]:
import pickle

In [2]:
with open('HA_Model.pkl', 'rb') as f:
    m = pickle.load(f)

In [46]:
m.predict([X_test[3]])[0] == 1

False

In [ ]:
min(heart['oldpeak'])

In [20]:
X_test[3]

array([ 60. ,   1. ,   0. , 125. , 258. ,   0. , 141. ,   1. ,   2.8,
        97.5])

In [22]:
Y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1], dtype=int64)